name: testworks
on:
  workflow_dispatch:
jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache
      CCACHE_MAXSIZE: 8G
    steps:
      - name: 测试路径
        run: |
          FILE_PATH=".github/workflows/Bin/main.bin"
          if [ -f "$FILE_PATH" ]; then
            echo "找到文件"
          else
            echo "错误：找不到文件 $FILE_PATH"
            ls -la .github/workflows/
            exit 1
          fi
