name: testworks
on:
  workflow_dispatch:
jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache
      CCACHE_MAXSIZE: 8G
    steps:
      - name: Check if build artifact exists
        run: |
          echo "仓库路径: $GITHUB_WORKSPACE"
          echo "工作流路径: ${{ github.workflow }}"
          echo "当前目录: $(pwd)"
          echo "仓库内容:"
          ls -laR
